routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SolicitudFondoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Auth\LoginController::class , 'showLoginForm']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('distritals', App\Http\Controllers\DistritalController::class);


Route::resource('estacionamientos', App\Http\Controllers\EstacionamientoController::class);


Route::resource('gerentes', App\Http\Controllers\GerenteController::class);


Route::resource('pagoAprovados', App\Http\Controllers\PagoAprovadoController::class);


Route::resource('solicitudFondos', App\Http\Controllers\SolicitudFondoController::class);

Route::post('solicitudFondos/aprobar', [App\Http\Controllers\SolicitudFondoController::class, 'aprobar'])->name('solicitudFondos.aprobar');

Route::get('/pdfPen/{id}', [App\Http\Controllers\SolicitudFondoController::class, 'downloadPdf'])->name('pdfPen');
Route::resource('users', App\Http\Controllers\UsersController::class);

app/Models/PagoAprovado.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class PagoAprovado
 * @package App\Models
 * @version February 3, 2022, 8:02 pm UTC
 *
 * @property \App\Models\User $idApruebaUsuarios
 * @property \App\Models\SolicitudFondo $idEstacionamientoPaga
 * @property \App\Models\SolicitudFondo $idSolicitudFondo
 * @property integer $id_aprueba_usuarios
 * @property string $tipo_pago
 * @property number $monto_pago
 * @property string $fecha_pago
 * @property integer $id_estacionamiento_paga
 * @property integer $id_solicitud_fondo
 * @property string $folio_anticipo
 * @property string $observaciones
 */
class PagoAprovado extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'pagos_aprobados';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'id_aprueba_usuarios',
        'tipo_pago',
        'monto_pago',
        'fecha_pago',
        'id_estacionamiento_paga',
        'id_solicitud_fondo',
        'folio_anticipo',
        'observaciones'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_aprueba_usuarios' => 'integer',
        'tipo_pago' => 'string',
        'monto_pago' => 'decimal:2',
        'fecha_pago' => 'date',
        'id_estacionamiento_paga' => 'integer',
        'id_solicitud_fondo' => 'integer',
        'folio_anticipo' => 'string',
        'observaciones' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_aprueba_usuarios' => 'nullable',
        'tipo_pago' => 'nullable|string|max:255',
        'monto_pago' => 'nullable|numeric',
        'fecha_pago' => 'nullable',
        'id_estacionamiento_paga' => 'nullable|integer',
        'id_solicitud_fondo' => 'nullable|integer',
        'folio_anticipo' => 'nullable|string|max:255',
        'observaciones' => 'nullable|string|max:1000',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idApruebaUsuarios()
    {
        return $this->belongsTo(\App\Models\User::class, 'id_aprueba_usuarios');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idEstacionamientoPaga()
    {
        return $this->belongsTo(\App\Models\SolicitudFondo::class, 'id_estacionamiento_paga');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idSolicitudFondo()
    {
        return $this->belongsTo(\App\Models\SolicitudFondo::class, 'id_solicitud_fondo');
    }
}

app/Http/Controllers/PagoAprovadoController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\AppBaseController;
use App\Repositories\PagoAprovadoRepository;
use App\Http\Requests\CreatePagoAprovadoRequest;
use App\Http\Requests\UpdatePagoAprovadoRequest;

class PagoAprovadoController extends AppBaseController
{
    /** @var PagoAprovadoRepository $pagoAprovadoRepository*/
    private $pagoAprovadoRepository;

    public function __construct(PagoAprovadoRepository $pagoAprovadoRepo)
    {
        $this->pagoAprovadoRepository = $pagoAprovadoRepo;
    }

    /**
     * Display a listing of the PagoAprovado.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $pagoAprovados = $this->pagoAprovadoRepository->all();

        return view('pago_aprovados.index')
            ->with('pagoAprovados', $pagoAprovados);
    }

    /**
     * Show the form for creating a new PagoAprovado.
     *
     * @return Response
     */
    public function create()
    {

        return view('pago_aprovados.create');
    }

    /**
     * Store a newly created PagoAprovado in storage.
     *
     * @param CreatePagoAprovadoRequest $request
     *
     * @return Response
     */
    public function store(CreatePagoAprovadoRequest $request)
    {
        $input = $request->all();

        $pagoAprovado = $this->pagoAprovadoRepository->create($input);

        Flash::success('Pago Aprovado saved successfully.');

        return redirect(route('pagoAprovados.index'));
    }

    /**
     * Display the specified PagoAprovado.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $pagoAprovado = $this->pagoAprovadoRepository->find($id);

        if (empty($pagoAprovado)) {
            Flash::error('Pago Aprovado not found');

            return redirect(route('pagoAprovados.index'));
        }

        return view('pago_aprovados.show')->with('pagoAprovado', $pagoAprovado);
    }

    /**
     * Show the form for editing the specified PagoAprovado.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $pagoAprovado = $this->pagoAprovadoRepository->find($id);

        if (empty($pagoAprovado)) {
            Flash::error('Pago Aprovado not found');

            return redirect(route('pagoAprovados.index'));
        }

        return view('pago_aprovados.edit')->with('pagoAprovado', $pagoAprovado);
    }

    /**
     * Update the specified PagoAprovado in storage.
     *
     * @param int $id
     * @param UpdatePagoAprovadoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePagoAprovadoRequest $request)
    {
        $pagoAprovado = $this->pagoAprovadoRepository->find($id);

        if (empty($pagoAprovado)) {
            Flash::error('Pago Aprovado not found');

            return redirect(route('pagoAprovados.index'));
        }

        $pagoAprovado = $this->pagoAprovadoRepository->update($request->all(), $id);

        Flash::success('Pago Aprovado updated successfully.');

        return redirect(route('pagoAprovados.index'));
    }

    /**
     * Remove the specified PagoAprovado from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $pagoAprovado = $this->pagoAprovadoRepository->find($id);

        if (empty($pagoAprovado)) {
            Flash::error('Pago Aprovado not found');

            return redirect(route('pagoAprovados.index'));
        }

        $this->pagoAprovadoRepository->delete($id);

        Flash::success('Pago Aprovado deleted successfully.');

        return redirect(route('pagoAprovados.index'));
    }
}

resources/views/pago_aprovados/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Pago Aprovado</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'pagoAprovados.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('pago_aprovados.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('pagoAprovados.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/pago_aprovados/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Pago Aprovado</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($pagoAprovado, ['route' => ['pagoAprovados.update', $pagoAprovado->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('pago_aprovados.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('pagoAprovados.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/pago_aprovados/fields.blade.php
<!-- Id Aprueba Usuarios Field -->
{!! Form::hidden('id_aprueba_usuarios', Auth::user()->id, ['class' => 'form-control']) !!}

<!-- Tipo Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipo_pago', 'Tipo Pago:') !!}
    <br>
    <select name="tipo_pago" id="tipo_pago" required>
        <option value="">Seleccione una opción</option>
        <option value="APROBACIÓN">APROBACIÓN</option>
        <option value="ANTICIPO">ANTICIPO</option>
        <option value="REEMBOLSO">REEMBOLSO</option>
        <option value="COMPROBACIÓN">COMPROBACIÓN</option>
    </select>
</div>

<!-- Monto Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('monto_pago', 'Monto Pago:') !!}
    {!! Form::number('monto_pago', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_pago', 'Fecha Pago:') !!}
    {!! Form::text('fecha_pago', null, ['class' => 'form-control', 'id' => 'fecha_pago']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha_pago').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Id Estacionamiento Paga Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_estacionamiento_paga', 'Id Estacionamiento Paga:') !!}
    {!! Form::number('id_estacionamiento_paga', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Solicitud Fondo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_solicitud_fondo', 'Id Solicitud Fondo:') !!}
    {!! Form::number('id_solicitud_fondo', null, ['class' => 'form-control']) !!}
</div>

<!-- Folio Anticipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('folio_anticipo', 'Folio Anticipo:') !!}
    {!! Form::text('folio_anticipo', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control', 'maxlength' => 1000, 'maxlength' => 1000]) !!}
</div>

resources/views/pago_aprovados/fieldsedit.blade.php
<!-- Id Aprueba Usuarios Field -->
{!! Form::hidden('id_aprueba_usuarios', Auth::user()->id, ['class' => 'form-control']) !!}

<!-- Tipo Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipo_pago', 'Tipo Pago:') !!}
    {!! Form::text('tipo_pago', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div>

<!-- Monto Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('monto_pago', 'Monto Pago:') !!}
    {!! Form::number('monto_pago', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_pago', 'Fecha Pago:') !!}
    {!! Form::text('fecha_pago', null, ['class' => 'form-control', 'id' => 'fecha_pago']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha_pago').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Id Estacionamiento Paga Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_estacionamiento_paga', 'Id Estacionamiento Paga:') !!}
    {!! Form::number('id_estacionamiento_paga', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Solicitud Fondo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_solicitud_fondo', 'Id Solicitud Fondo:') !!}
    {!! Form::number('id_solicitud_fondo', null, ['class' => 'form-control']) !!}
</div>

<!-- Folio Anticipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('folio_anticipo', 'Folio Anticipo:') !!}
    {!! Form::text('folio_anticipo', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control', 'maxlength' => 1000, 'maxlength' => 1000]) !!}
</div>

resources/views/pago_aprovados/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Pago Aprobados</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('pagoAprovados.create') }}">
                        Añadir
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('pago_aprovados.table')

                <div class="card-footer clearfix">
                    <div class="float-right">

                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/pago_aprovados/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Pago Aprovado Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('pagoAprovados.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('pago_aprovados.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pago_aprovados/show_fields.blade.php
<!-- Id Aprueba Usuarios Field -->
<div class="col-sm-12">
    {!! Form::label('id_aprueba_usuarios', 'Id Aprueba Usuarios:') !!}
    <p>{{ $pagoAprovado->id_aprueba_usuarios }}</p>
</div>

<!-- Tipo Pago Field -->
<div class="col-sm-12">
    {!! Form::label('tipo_pago', 'Tipo Pago:') !!}
    <p>{{ $pagoAprovado->tipo_pago }}</p>
</div>

<!-- Monto Pago Field -->
<div class="col-sm-12">
    {!! Form::label('monto_pago', 'Monto Pago:') !!}
    <p>{{ $pagoAprovado->monto_pago }}</p>
</div>

<!-- Fecha Pago Field -->
<div class="col-sm-12">
    {!! Form::label('fecha_pago', 'Fecha Pago:') !!}
    <p>{{ $pagoAprovado->fecha_pago }}</p>
</div>

<!-- Id Estacionamiento Paga Field -->
<div class="col-sm-12">
    {!! Form::label('id_estacionamiento_paga', 'Id Estacionamiento Paga:') !!}
    <p>{{ $pagoAprovado->id_estacionamiento_paga }}</p>
</div>

<!-- Id Solicitud Fondo Field -->
<div class="col-sm-12">
    {!! Form::label('id_solicitud_fondo', 'Id Solicitud Fondo:') !!}
    <p>{{ $pagoAprovado->id_solicitud_fondo }}</p>
</div>

<!-- Folio Anticipo Field -->
<div class="col-sm-12">
    {!! Form::label('folio_anticipo', 'Folio Anticipo:') !!}
    <p>{{ $pagoAprovado->folio_anticipo }}</p>
</div>

<!-- Observaciones Field -->
<div class="col-sm-12">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    <p>{{ $pagoAprovado->observaciones }}</p>
</div>

resources/views/pago_aprovados/table.blade.php
<div class="table-responsive">
    <table class="table" id="pagoAprovados-table">
        <thead>
            <tr>
                <th>Aprueba Usuarios</th>
                <th>Tipo Pago</th>
                <th>Monto Pago</th>
                <th>Fecha Pago</th>
                <th>Estacionamiento Paga</th>
                <th>Folio Anticipo</th>
                <th>Observaciones</th>
                <th>Solicitud Fondo</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($pagoAprovados as $pagoAprovado)
                <tr>
                    <td>{{ $pagoAprovado->idApruebaUsuarios->name }}</td>
                    <td>{{ $pagoAprovado->tipo_pago }}</td>
                    <td>
                        @if ($pagoAprovado->monto_pago == 0)
                            Pendiente de actualización
                        @else
                            {{ $pagoAprovado->monto_pago }}
                        @endif
                    </td>
                    <td>
                        @if (is_null($pagoAprovado->fecha_pago))
                            Pendiente de actualización
                        @else
                            {{ $pagoAprovado->fecha_pago }}
                        @endif
                    </td>
                    <td>{{ $pagoAprovado->id_estacionamiento_paga }}</td>
                    <td>{{ $pagoAprovado->folio_anticipo }}</td>
                    <td>{{ $pagoAprovado->observaciones }}</td>
                    <td>{{ $pagoAprovado->id_solicitud_fondo }} </td>
                    {!! Form::open(['route' => ['pagoAprovados.destroy', $pagoAprovado->id], 'method' => 'delete']) !!}
                    <td width="120">
                        <a href="{{ route('pagoAprovados.edit', [$pagoAprovado->id]) }}"
                            class='btn btn-primary btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                    </td>
                    <td>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </td>
                    {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#pagoAprovados-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
                }
            });
        });
    </script>
@endsection