routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SolicitudFondoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Auth\LoginController::class , 'showLoginForm']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('distritals', App\Http\Controllers\DistritalController::class);


Route::resource('estacionamientos', App\Http\Controllers\EstacionamientoController::class);


Route::resource('gerentes', App\Http\Controllers\GerenteController::class);


Route::resource('pagoAprovados', App\Http\Controllers\PagoAprovadoController::class);


Route::resource('solicitudFondos', App\Http\Controllers\SolicitudFondoController::class);

Route::post('solicitudFondos/aprobar', [App\Http\Controllers\SolicitudFondoController::class, 'aprobar'])->name('solicitudFondos.aprobar');

Route::get('/pdfPen/{id}', [App\Http\Controllers\SolicitudFondoController::class, 'downloadPdf'])->name('pdfPen');
Route::resource('users', App\Http\Controllers\UsersController::class);

app/Models/SolicitudFondo.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SolicitudFondo
 *
 * @property int $id
 * @property int|null $id_estacionamiento
 * @property string|null $tipo_solicitud
 * @property string|null $concepto
 * @property float|null $importe_solicitado
 * @property Carbon|null $fecha_ingreso_finanzas
 * @property Carbon|null $fecha_entrega_cxp
 * @property Carbon|null $fecha_ingreso_cxp
 * @property string|null $estatus_registro
 * @property string|null $estatus_peticion
 * @property string|null $observaciones
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property string|null $folio_documento
 *
 * @property Collection|ComprobantesGasto[] $comprobantes_gastos
 * @property Collection|PagosAprobado[] $pagos_aprobados
 *
 * @package App\Models
 */
class SolicitudFondo extends Model
{
	use SoftDeletes;
	protected $table = 'solicitud_fondos';

	protected $casts = [
		'id_estacionamiento' => 'int',
		'importe_solicitado' => 'float'
	];

	protected $dates = [
		'fecha_ingreso_finanzas',
		'fecha_entrega_cxp',
		'fecha_ingreso_cxp'
	];

	protected $fillable = [
		'id_estacionamiento',
		'tipo_solicitud',
		'concepto',
		'importe_solicitado',
		'fecha_ingreso_finanzas',
		'fecha_entrega_cxp',
		'fecha_ingreso_cxp',
		'estatus_registro',
		'estatus_peticion',
		'observaciones',
		'folio_documento',
        'procedencia',
	];

	public function comprobantes_gastos()
	{
		return $this->hasMany(ComprobantesGasto::class, 'id_solicitud_fondos');
	}

	public function pagos_aprobados()
	{
		return $this->hasMany(PagosAprobado::class, 'id_solicitud_fondo');
	}
}

app/Http/Controllers/SolicitudFondoController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Response;
use App\Models\PagoAprovado;
use Illuminate\Http\Request;
use App\Models\SolicitudFondo;
use App\Models\ComprobantesGasto;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AppBaseController;
use App\Repositories\SolicitudFondoRepository;
use App\Http\Requests\CreateSolicitudFondoRequest;
use App\Http\Requests\UpdateSolicitudFondoRequest;

class SolicitudFondoController extends AppBaseController
{
    /** @var SolicitudFondoRepository $solicitudFondoRepository*/
    private $solicitudFondoRepository;

    public function __construct(SolicitudFondoRepository $solicitudFondoRepo)
    {
        $this->solicitudFondoRepository = $solicitudFondoRepo;
    }

    /**
     * Display a listing of the SolicitudFondo.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $solicitudFondos = SolicitudFondo::with('comprobantes_gastos')->where('estatus_peticion', '!=', 'Autoriza Sergio')->orderByDesc('id')->get();

        return view('solicitud_fondos.index')
            ->with('solicitudFondos', $solicitudFondos);
    }

    /**
     * Show the form for creating a new SolicitudFondo.
     *
     * @return Response
     */
    public function create()
    {
        $estacionamientos = DB::connection('mysql2')->SELECT('SELECT * FROM parks');
        return view('solicitud_fondos.create', compact('estacionamientos'));
    }

    /**
     * Store a newly created SolicitudFondo in storage.
     *
     * @param CreateSolicitudFondoRequest $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $solicitudFondo = $this->solicitudFondoRepository->create($input);

        Flash::success('Solicitud añadida.');

        return redirect(route('solicitudFondos.index'));
    }

    /**
     * Display the specified SolicitudFondo.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $solicitudFondo = $this->solicitudFondoRepository->find($id);

        if (empty($solicitudFondo)) {
            Flash::error('Solicitud Fondo not found');

            return redirect(route('solicitudFondos.index'));
        }

        return view('solicitud_fondos.show')->with('solicitudFondo', $solicitudFondo);
    }

    /**
     * Show the form for editing the specified SolicitudFondo.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $solicitudFondo = $this->solicitudFondoRepository->find($id);

        if (empty($solicitudFondo)) {
            Flash::error('Solicitud Fondo not found');

            return redirect(route('solicitudFondos.index'));
        }

        $estacionamientos = DB::connection('mysql2')->SELECT('SELECT * FROM parks');

        return view('solicitud_fondos.edit', compact('estacionamientos'))->with('solicitudFondo', $solicitudFondo);
    }

    /**
     * Update the specified SolicitudFondo in storage.
     *
     * @param int $id
     * @param UpdateSolicitudFondoRequest $request
     *
     * @return Response
     */
    public function update($id, Request $request)
    {
        $solicitudFondo = $this->solicitudFondoRepository->find($id);

        if (empty($solicitudFondo)) {
            Flash::error('Solicitud Fondo not found');

            return redirect(route('solicitudFondos.index'));
        }

        $solicitudFondo = $this->solicitudFondoRepository->update($request->all(), $id);

        Flash::success('Solicitud actualizado.');

        return redirect(route('solicitudFondos.index'));
    }

    /**
     * Remove the specified SolicitudFondo from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $solicitudFondo = $this->solicitudFondoRepository->find($id);

        if (empty($solicitudFondo)) {
            Flash::error('Solicitud Fondo not found');

            return redirect(route('solicitudFondos.index'));
        }

        $this->solicitudFondoRepository->delete($id);

        Flash::success('Solicitud eliminado.');

        return redirect(route('solicitudFondos.index'));
    }

    public function aprobar(Request $request)
    {
        $solicitudFondo = SolicitudFondo::find($request->id);
        $solicitudFondo->estatus_peticion = $request->estatus_peticion;
        $solicitudFondo->save();

        $pagoaprobado = PagoAprovado::create([
            'id_aprueba_usuarios' => Auth::user()->id,
            'tipo_pago' => 'Pendiente de actualización',
            'monto_pago' => '0',
            'fecha_pago' => null,
            'id_estacionamiento_paga' => $solicitudFondo->id_estacionamiento,
            'id_solicitud_fondo' => $solicitudFondo->id,
            'folio_anticipo' => $solicitudFondo->solicitud_documentos,
            'observaciones' => $solicitudFondo->observaciones,
        ]);

        Flash::success('Solicitud con estatus actualizado.');

        return redirect(route('solicitudFondos.index'));
    }

    public function downloadPdf($id)
    {
        $pdf = ComprobantesGasto::find($id);
        $archivo = $pdf->documento;
        $decoded = base64_decode($archivo);
        $path = "pdfs/" . $pdf->id . ".pdf";
        file_put_contents($path, $decoded);
        header("Content-disposition: attachment; filename=$pdf->nombre");
        header("Content-type: application/pdf");
        readfile($path);
        unlink($path);
    }
}

resources/views/solicitud_fondos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Crear Solicitud Fondo</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'solicitudFondos.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('solicitud_fondos.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('solicitudFondos.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/solicitud_fondos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Editar</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($solicitudFondo, ['route' => ['solicitudFondos.update', $solicitudFondo->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('solicitud_fondos.fieldsedit')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('solicitudFondos.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/solicitud_fondos/fields.blade.php
<!-- Id Estacionamiento Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_estacionamiento', 'Estacionamiento:') !!}
    <br>
    <select name="id_estacionamiento" id="id_estacionamiento" required>
        <option value="" >Seleccione una opción</option>
        @foreach ($estacionamientos as $est)
            <option value="{{$est->no_est}}">({{$est->no_est}}) / {{$est->nombre}}</option>
        @endforeach
    </select>
</div>

<!-- Tipo Solicitud Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipo_solicitud', 'Tipo Solicitud:') !!}
    <br>
    {!! Form::select(
    'tipo_solicitud',
    ['' => 'Seleccione una opción', 'Anticipo' => 'Anticipo', 'Comprobación' => 'Comprobación', 'Reembolso' => 'Reembolso'],
    [
        'class' => 'form-control',
        'placeholder' => 'Seleccione un tipo de solicitud',
    ],
) !!}

</div>

<!-- Concepto Field -->
<div class="form-group col-sm-6">
    {!! Form::label('concepto', 'Concepto:') !!}
    {!! Form::text('concepto', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div>

<!-- Importe Solicitado Field -->
<div class="form-group col-sm-6">
    {!! Form::label('importe_solicitado', 'Importe Solicitado:') !!}
    {!! Form::number('importe_solicitado', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Ingreso Finanzas Field -->
<div class="form-group col-sm-6">
    @php
        $horaactual = Carbon\Carbon::now();
    @endphp
    {!! Form::label('fecha_ingreso_finanzas', 'Fecha Ingreso Finanzas:') !!}
    {!! Form::text('fecha_ingreso_finanzas', $horaactual->toDateString('Y-m-d'), ['class' => 'form-control', 'id' => 'fecha_ingreso_finanzas', 'readonly']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha_ingreso_finanzas').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

{!! Form::hidden('fecha_entrega_cxp', $horaactual->toDateTimeString(), ['class' => 'form-control', 'id' => 'fecha_entrega_cxp']) !!}

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha_entrega_cxp').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Fecha Ingreso Cxp Field -->
{!! Form::hidden('fecha_ingreso_cxp', $horaactual->toDateTimeString(), ['class' => 'form-control', 'id' => 'fecha_ingreso_cxp']) !!}


@push('page_scripts')
    <script type="text/javascript">
            format: 'YYYY-MM-DD HH:mm:ss',
        $('#fecha_ingreso_cxp').datetimepicker({
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Estatus Registro Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estatus_registro', 'Estatus Registro:') !!}
    <br>
    {!! Form::select(
    'estatus_registro',
    ['' => 'Seleccione una opción','Registrado' => 'Registrado', 'Capturado' => 'Capturado'],
    [
        'class' => 'form-control',
        'placeholder' => 'Seleccione un estatus',
    ],
) !!}
</div>

<!-- Estatus Peticion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estatus_peticion', 'Estatus Peticion:') !!}
    <br>
    {!! Form::select(
    'estatus_peticion',
    ['' => 'Seleccione una opción','Autoriza Sergio' => 'Autoriza Sergio', 'Rechazado' => 'Rechazado', 'Reingresado' => 'Reingresado', 'N/A' => 'N/A'],
    [
        'class' => 'form-control',
        'placeholder' => 'Seleccione un estatus',
    ],
) !!}
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control', 'maxlength' => 1000, 'maxlength' => 1000]) !!}
</div>

resources/views/solicitud_fondos/fieldsedit.blade.php
<!-- Id Estacionamiento Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_estacionamiento', 'Estacionamiento:') !!}
    <br>
    <select name="id_estacionamiento" id="id_estacionamiento" required>
        <option value="" >Seleccione una opción</option>
        @foreach ($estacionamientos as $est)
            <option value="{{$est->no_est}}" {{ ( $est->no_est == $solicitudFondo->id_estacionamiento) ? 'selected' : '' }}>({{$est->no_est}}) / {{$est->nombre}}</option>
        @endforeach
    </select>
</div>

<!-- Tipo Solicitud Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipo_solicitud', 'Tipo Solicitud:') !!}
    <br>
    {!! Form::select(
    'tipo_solicitud',
    ['' => 'Seleccione una opción', 'Anticipo' => 'Anticipo', 'Comprobación' => 'Comprobación', 'Reembolso' => 'Reembolso'],
    $solicitudFondo->tipo_solicitud,
    [
        'class' => 'form-control',
        'placeholder' => 'Seleccione un tipo de solicitud',
    ],
) !!}

</div>

<!-- Concepto Field -->
<div class="form-group col-sm-6">
    {!! Form::label('concepto', 'Concepto:') !!}
    {!! Form::text('concepto', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div>

<!-- Importe Solicitado Field -->
<div class="form-group col-sm-6">
    {!! Form::label('importe_solicitado', 'Importe Solicitado:') !!}
    {!! Form::number('importe_solicitado', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Ingreso Finanzas Field -->
<div class="form-group col-sm-6">
    @php
        $horaactual = Carbon\Carbon::now();
    @endphp
    {!! Form::label('fecha_ingreso_finanzas', 'Fecha Ingreso Finanzas:') !!}
    {!! Form::text('fecha_ingreso_finanzas', null, ['class' => 'form-control', 'id' => 'fecha_ingreso_finanzas', 'readonly']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha_ingreso_finanzas').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

{!! Form::hidden('fecha_entrega_cxp', $horaactual->toDateTimeString(), ['class' => 'form-control', 'id' => 'fecha_entrega_cxp']) !!}

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha_entrega_cxp').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Fecha Ingreso Cxp Field -->
{!! Form::hidden('fecha_ingreso_cxp', $horaactual->toDateTimeString(), ['class' => 'form-control', 'id' => 'fecha_ingreso_cxp']) !!}


@push('page_scripts')
    <script type="text/javascript">
            format: 'YYYY-MM-DD HH:mm:ss',
        $('#fecha_ingreso_cxp').datetimepicker({
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Estatus Registro Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estatus_registro', 'Estatus Registro:') !!}
    <br>
    {!! Form::select(
    'estatus_registro',
    ['Registrado' => 'Registrado', 'Capturado' => 'Capturado'],
    $solicitudFondo->estatus_registro,
    [
        'class' => 'form-control',
        'placeholder' => 'Seleccione un estatus',
    ],
) !!}
</div>

<!-- Estatus Peticion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estatus_peticion', 'Estatus Peticion:') !!}
    <br>
    {!! Form::select(
    'estatus_peticion',
    ['Autoriza Sergio' => 'Autoriza Sergio', 'Rechazado' => 'Rechazado', 'Reingresado' => 'Reingresado', 'N/A' => 'N/A'],
    $solicitudFondo->estatus_peticion,
    [
        'class' => 'form-control',
        'placeholder' => 'Seleccione un estatus',
    ],
) !!}
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control', 'maxlength' => 1000, 'maxlength' => 1000]) !!}
</div>

resources/views/solicitud_fondos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Solicitud Fondos</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('solicitudFondos.create') }}">
                        Añadir
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('solicitud_fondos.table')

                <div class="card-footer clearfix">
                    <div class="float-right">

                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/solicitud_fondos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Solicitud Fondo Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('solicitudFondos.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('solicitud_fondos.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/solicitud_fondos/table.blade.php
<div class="table-responsive">
    <table class="table" id="solicitudFondos-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Folio</th>
                <th>Estacionamiento</th>
                <th>Tipo Solicitud</th>
                <th>Concepto</th>
                <th>Importe memo</th>
                <th>Fecha Ingreso Finanzas</th>
                {{-- <th>Fecha Entrega Cxp</th>
                <th>Fecha Ingreso Cxp</th> --}}
                <th>Estatus Registro</th>
                <th>Estatus Peticion</th>
                <th>Observaciones</th>
                <th>Procedencia</th>
                <th>Documento</th>
                <th>Aceptar/Rechazar</th>
                <th>Editar</th>
                <th>Eliminar</th>

            </tr>
        </thead>
        <tbody>
            @foreach ($solicitudFondos as $solicitudFondo)
                <tr>
                    <td>{!! $solicitudFondo->id !!}</td>
                    <td>{!! $solicitudFondo->folio_documento !!}</td>
                    <td>{{ $solicitudFondo->id_estacionamiento }}</td>
                    <td>{{ $solicitudFondo->tipo_solicitud }}</td>
                    <td>{{ $solicitudFondo->concepto }}</td>
                    <td>{{ $solicitudFondo->importe_solicitado }}</td>
                    <td>{{ date('d-m-Y', strtotime($solicitudFondo->fecha_ingreso_finanzas)) }}</td>
                    {{-- <td>{{ $solicitudFondo->fecha_entrega_cxp }}</td>
                    <td>{{ $solicitudFondo->fecha_ingreso_cxp }}</td> --}}
                    <td>{{ $solicitudFondo->estatus_registro }}</td>
                    <td>{{ $solicitudFondo->estatus_peticion }}</td>
                    <td>{{ $solicitudFondo->observaciones }}</td>
                    <td>{{ $solicitudFondo->procedencia }}</td>
                    <td>
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                            data-target="#exampleModal{!! $solicitudFondo->id !!}">
                            Ver
                        </button>
                    </td>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{!! $solicitudFondo->id !!}" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Documentos</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @foreach ($solicitudFondo->comprobantes_gastos as $item)
                                        <ul>
                                            <li><a href="{{ url('pdfPen/' . $item->id_comprobantes) }}"
                                                    class='btn-floating btn-sm btn-blue-grey'>{!! $item->nombre !!}</a>
                                            </li>
                                        </ul>
                                    @endforeach
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <td width="120">
                        <button type="button" class='btn btn-success btn-xs' data-toggle="modal"
                            data-target="#valida{!! $solicitudFondo->id !!}">
                            <i class="fas fa-check-circle"></i>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="valida{!! $solicitudFondo->id !!}" tabindex="-1" role="dialog"
                            aria-labelledby="validaLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="validaLabel">Actualizar estatus</h5>
                                        <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form method="POST" action="{{ route('solicitudFondos.aprobar') }}"
                                            enctype="multipart/form-data">
                                            @csrf
                                            <select name="estatus_peticion" required>
                                                <option value="" selected>Seleccione un estatus*</option>
                                                <option value="Autoriza Sergio">Autoriza Sergio</option>
                                                <option value="Rechazado">Rechazado</option>
                                                <option value="Reingresado">Reingresado</option>
                                                <option value="N/A">N/A</option>
                                            </select>
                                            {!! Form::hidden('id', $solicitudFondo->id) !!}
                                            <br><br>
                                            <button type="submit" class="btn btn-primary">Enviar</button>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    {!! Form::open(['route' => ['solicitudFondos.destroy', $solicitudFondo->id], 'method' => 'delete']) !!}
                    <td width="120">
                        <a href="{{ route('solicitudFondos.edit', [$solicitudFondo->id]) }}"
                            class='btn btn-primary btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                    </td>
                    <td width="120">
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </td>
                    {!! Form::close() !!}
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#solicitudFondos-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
                }
            });
        });
    </script>
@endsection