routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SolicitudFondoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Auth\LoginController::class , 'showLoginForm']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('distritals', App\Http\Controllers\DistritalController::class);


Route::resource('estacionamientos', App\Http\Controllers\EstacionamientoController::class);


Route::resource('gerentes', App\Http\Controllers\GerenteController::class);


Route::resource('pagoAprovados', App\Http\Controllers\PagoAprovadoController::class);


Route::resource('solicitudFondos', App\Http\Controllers\SolicitudFondoController::class);

Route::post('solicitudFondos/aprobar', [App\Http\Controllers\SolicitudFondoController::class, 'aprobar'])->name('solicitudFondos.aprobar');

Route::get('/pdfPen/{id}', [App\Http\Controllers\SolicitudFondoController::class, 'downloadPdf'])->name('pdfPen');
Route::resource('users', App\Http\Controllers\UsersController::class);

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap4.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
{{-- <li class="nav-item">
    <a href="{{ route('distritals.index') }}"
       class="nav-link {{ Request::is('distritals*') ? 'active' : '' }}">
        <p>Distritals</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('estacionamientos.index') }}"
       class="nav-link {{ Request::is('estacionamientos*') ? 'active' : '' }}">
        <p>Estacionamientos</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('gerentes.index') }}"
       class="nav-link {{ Request::is('gerentes*') ? 'active' : '' }}">
        <p>Gerentes</p>
    </a>
</li> --}}


<li class="nav-item">
    <a href="{{ route('pagoAprovados.index') }}"
       class="nav-link {{ Request::is('pagoAprovados*') ? 'active' : '' }}">
        <p>Pago Aprobados</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('solicitudFondos.index') }}"
       class="nav-link {{ Request::is('solicitudFondos*') ? 'active' : '' }}">
        <p>Solicitud Fondos</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('users.index') }}"
       class="nav-link {{ Request::is('users*') ? 'active' : '' }}">
        <p>Usuarios</p>
    </a>
</li>